#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "labels", "name")
#@ load("env.lib.yaml", "merge_env")

#@ def extra_env():
- name: REDIS_REPLICATION_MODE
  value: slave
- name: REDIS_MASTER_HOST
  value: #@ name("master")
#@ end

#@ _name = name("slave")
#@ _labels = labels("slave")

#@ if/end data.values.slave.enabled:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ _name
  labels: #@ _labels
spec:
  replicas: #@ data.values.slave.replicas
  selector:
    matchLabels: #@ _labels
  template:
    metadata:
      labels: #@ _labels
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: default
      containers:
      - name: redis
        image: #@ data.values.image
        env: #@ merge_env(data.values.slave.env, extra_env())
        resources: #@ data.values.slave.resources
        ports:
        - containerPort: 6379
          name: redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
      - name: redis-exporter
        image: #@ data.values.exporter.image
        env: #@ data.values.exporter.env
        resources: #@ data.values.exporter.resources
        ports:
        - containerPort: 9121
          name: metrics
