#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "labels", "name")

#@ def service(role="", sts=False):
apiVersion: v1
kind: Service
metadata:
  name: #@ name(role)
  labels: #@ labels(role)
spec:
  #@ if/end sts:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  - name: metrics
    port: 9121
    targetPort: metrics
  selector: #@ labels(role)
#@ end

--- #@ service("master", True)
#@ if/end data.values.slave.enabled:
--- #@ service("slave")
