#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "labels", "name")
#@ load("env.lib.yaml", "merge_env")

#@ def extra_env():
- name: REDIS_REPLICATION_MODE
  value: master
#@ end

#@ _name = name("master")
#@ _labels = labels("master")
#@ _service_name = _name
#@ _storage_name = _name + "-data"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: #@ _name
  labels: #@ _labels
spec:
  replicas: 1
  selector:
    matchLabels: #@ _labels
  serviceName: #@ _service_name
  template:
    metadata:
      labels: #@ _labels
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
      - name: redis
        image: #@ data.values.image
        env: #@ merge_env(data.values.master.env, extra_env())
        resources: #@ data.values.master.resources
        ports:
        - containerPort: 6379
          name: redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
        volumeMounts:
        - mountPath: /bitnami/redis/data
          name: #@ _storage_name
      - name: redis-exporter
        image: #@ data.values.exporter.image
        env: #@ data.values.exporter.env
        resources: #@ data.values.exporter.resources
        ports:
        - containerPort: 9121
          name: metrics
  volumeClaimTemplates:
    - metadata:
        name: #@ _storage_name
        labels: #@ _labels
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: #@ data.values.master.storage
