#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "labels")
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.name
  labels: #@ labels
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 24231
      targetPort: metrics
    - name: http
      port: 9880
      targetPort: http
  selector: #@ labels
