#@ load("@ytt:data", "data")

#@ sa_name = "namespace-admin"

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ sa_name
  namespace: #@ data.values.namespace
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: #@ sa_name
  namespace: #@ data.values.namespace
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: #@ sa_name
  namespace: #@ data.values.namespace
subjects:
- kind: ServiceAccount
  name: #@ sa_name
  namespace: #@ data.values.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: #@ sa_name

